version: '3.6'

services:
    mysql:
        image: mysql
        environment: 
            MYSQL_USER: wordpress
            MYSQL_DATABASE: wordpress
            #MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_ROOT_PASSWORD_FILE: "/run/secrets/mysql_root_pass"

        secrets:
            - mysql_root_pass
        deploy:
            placement:
                constraints:
                    - node.role==manager
secrets:
    mysql_root_pass:
        external: true

