version: '3.1'

services:
    mysql:
        image: mysql
        environment: 
            MYSQL_USER: wordpress
            MYSQL_DATABASE: wordpress
            MYSQL_ROOT_PASSWORD_FILE: "/run/secrets/root_pass"
        secrets:
            - source: root_pass_v2
              target: root_pass
        deploy:
            placement:
                constraints:
                    - node.role==manager
