version: '3.1'

services:
    calc:
        image: swarmgs/calc
        ports:
            - "7000:80"
        deploy:
            placement:
                constraints:
                    - node.role==manager

